#!/bin/bash
source config

FILE_LIST=$(cd $SHARED_DIR ; find . -type f | grep -v \\.$ | cut -b 2-)
if [ $# -gt 0 ] ; then
    echo Creating source for $1
    mkdir -p $MACHINE_DIR/$1 
    for f in $FILE_LIST ; do
	scp -q $1:$f $MACHINE_DIR/$1/$f.before
	echo -n ". "
    done
    echo
    echo $1 source created
else

    read -n1 -p "Are you sure you want to recreate the complete source directory? (y/n) "
    echo
    [[ $REPLY = [yY] ]] && echo Creating source directory || { exit 1; }	
    for m in $MACHINE_LIST ; do 
	if [[ "$m" != "`hostname -s`" ]]; then
	    mkdir -p $MACHINE_DIR/$m 
	    for f in $FILE_LIST ; do
		scp -q $m:$f $MACHINE_DIR/$m/$f.before
	    done
	    echo -n ". "
	fi
    done
    echo
    echo source directory created
fi
